### ISSUE TITLE
Issue-updated to latest node template; fixed issues #1 and #2

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/test1#11]
Automated Review Comments
Issues in Cargo.toml:
  - (17, 'Hardcoded string found')
  - (32, 'Line exceeds 80 characters')
  - (35, 'Line exceeds 80 characters')
  - (36, 'Line exceeds 80 characters')
  - (37, 'Line exceeds 80 characters')
  - (38, 'Hardcoded string found')
  - (65, 'Hardcoded string found')
  - (78, 'Hardcoded string found')
  - (86, 'Hardcoded string found')
  - (121, 'Hardcoded string found')
  - (122, 'Hardcoded string found')
Issues in README.md:
  - (1, 'Line exceeds 80 characters')
  - (3, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
Issues in build.rs:
  - (23, 'Hardcoded string found')
Issues in runtime/Cargo.toml:
  - (145, 'Line exceeds 80 characters')
  - (147, 'Line exceeds 80 characters')
  - (154, 'Hardcoded string found')
  - (155, 'Hardcoded string found')
Issues in runtime/src/erc20.rs:
  - (4, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
  - (24, 'Line exceeds 80 characters')
  - (24, 'Hardcoded string found')
  - (25, 'Line exceeds 80 characters')
  - (27, 'Line exceeds 80 characters')
  - (28, 'Line exceeds 80 characters')
  - (32, 'Line exceeds 80 characters')
  - (39, 'Line exceeds 80 characters')
  - (44, 'Line exceeds 80 characters')
  - (45, 'Line exceeds 80 characters')
  - (47, 'Line exceeds 80 characters')
  - (48, 'Line exceeds 80 characters')
  - (55, 'Line exceeds 80 characters')
  - (65, 'Line exceeds 80 characters')
  - (68, 'Line exceeds 80 characters')
  - (71, 'Line exceeds 80 characters')
  - (79, 'Line exceeds 80 characters')
Issues in runtime/src/lib.rs:
  - (2, 'Line exceeds 80 characters')
  - (13, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (40, 'Line exceeds 80 characters')
  - (46, 'Line exceeds 80 characters')
  - (51, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
  - (72, 'Line exceeds 80 characters')
  - (81, 'Line exceeds 80 characters')
  - (87, 'Line exceeds 80 characters')
  - (119, 'Line exceeds 80 characters')
  - (136, 'Line exceeds 80 characters')
  - (140, 'Line exceeds 80 characters')
  - (142, 'Line exceeds 80 characters')
Issues in runtime/wasm/Cargo.toml:
  - (4, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (25, 'Line exceeds 80 characters')
  - (26, 'Line exceeds 80 characters')
  - (27, 'Line exceeds 80 characters')
  - (28, 'Line exceeds 80 characters')
  - (29, 'Line exceeds 80 characters')
  - (30, 'Line exceeds 80 characters')
  - (31, 'Line exceeds 80 characters')
  - (32, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')
  - (34, 'Line exceeds 80 characters')
  - (35, 'Line exceeds 80 characters')
  - (36, 'Line exceeds 80 characters')
  - (37, 'Line exceeds 80 characters')
  - (38, 'Line exceeds 80 characters')
  - (39, 'Line exceeds 80 characters')
  - (40, 'Line exceeds 80 characters')
  - (42, 'Hardcoded string found')
  - (67, 'Hardcoded string found')
Issues in runtime/wasm/build.sh:
  - (8, 'Line exceeds 80 characters')
Issues in runtime/wasm/src/lib.rs:
  - (4, 'Hardcoded string found')
Issues in src/chain_spec.rs:
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (18, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
  - (26, 'Line exceeds 80 characters')
Issues in src/cli.rs:
  - (8, 'Line exceeds 80 characters')
  - (20, 'Line exceeds 80 characters')
  - (24, 'Line exceeds 80 characters')
  - (32, 'Line exceeds 80 characters')
  - (56, 'Line exceeds 80 characters')
  - (72, 'Line exceeds 80 characters')
  - (73, 'Line exceeds 80 characters')
  - (78, 'Line exceeds 80 characters')
  - (83, 'Line exceeds 80 characters')
  - (95, 'Line exceeds 80 characters')
Issues in src/main.rs:
  - (32, 'Hardcoded string found')
Issues in src/service.rs:
  - (13, 'Line exceeds 80 characters')
  - (26, 'Line exceeds 80 characters')
  - (29, 'Line exceeds 80 characters')
  - (41, 'Line exceeds 80 characters')
  - (42, 'Line exceeds 80 characters')
  - (65, 'Line exceeds 80 characters')
  - (86, 'Line exceeds 80 characters')

**Comment by satomichru** [comment]
I got it.
