### ISSUE TITLE
Issue-initial commit

### ISSUE THREAD

**Issue by seriousfuzzy** [seriousfuzzy/test1#2]
Automated Review Comments
Issues in Cargo.toml:
  - (15, 'Hardcoded string found')
  - (30, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')
  - (34, 'Line exceeds 80 characters')
  - (35, 'Line exceeds 80 characters')
  - (36, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
Issues in LICENSE:
  - (17, 'Hardcoded string found')
Issues in build.rs:
  - (22, 'Hardcoded string found')
Issues in runtime/Cargo.toml:
  - (29, 'Line exceeds 80 characters')
  - (31, 'Line exceeds 80 characters')
  - (34, 'Hardcoded string found')
Issues in runtime/src/lib.rs:
  - (2, 'Line exceeds 80 characters')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (17, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (41, 'Line exceeds 80 characters')
  - (47, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (73, 'Line exceeds 80 characters')
  - (74, 'Line exceeds 80 characters')
  - (75, 'Line exceeds 80 characters')
  - (82, 'Hardcoded string found')
  - (83, 'Line exceeds 80 characters')
  - (83, 'Hardcoded string found')
  - (90, 'Line exceeds 80 characters')
  - (109, 'Line exceeds 80 characters')
  - (110, 'Hardcoded string found')
  - (121, 'Line exceeds 80 characters')
  - (148, 'Line exceeds 80 characters')
  - (160, 'Line exceeds 80 characters')
  - (164, 'Line exceeds 80 characters')
  - (172, 'Line exceeds 80 characters')
  - (186, 'Line exceeds 80 characters')
  - (199, 'Line exceeds 80 characters')
  - (206, 'Line exceeds 80 characters')
  - (225, 'Line exceeds 80 characters')
  - (229, 'Line exceeds 80 characters')
  - (266, 'Line exceeds 80 characters')
  - (285, 'Line exceeds 80 characters')
  - (295, 'Line exceeds 80 characters')
Issues in runtime/wasm/Cargo.lock:
  - (3, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (15, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
  - (37, 'Hardcoded string found')
  - (47, 'Line exceeds 80 characters')
  - (51, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
  - (65, 'Hardcoded string found')
  - (75, 'Hardcoded string found')
  - (85, 'Hardcoded string found')
  - (98, 'Hardcoded string found')
  - (107, 'Line exceeds 80 characters')
  - (108, 'Line exceeds 80 characters')
  - (118, 'Line exceeds 80 characters')
  - (133, 'Hardcoded string found')
  - (138, 'Hardcoded string found')
  - (151, 'Hardcoded string found')
  - (161, 'Line exceeds 80 characters')
  - (177, 'Line exceeds 80 characters')
  - (199, 'Line exceeds 80 characters')
  - (203, 'Hardcoded string found')
  - (212, 'Line exceeds 80 characters')
  - (226, 'Line exceeds 80 characters')
  - (235, 'Hardcoded string found')
  - (242, 'Line exceeds 80 characters')
  - (247, 'Line exceeds 80 characters')
  - (253, 'Hardcoded string found')
  - (265, 'Line exceeds 80 characters')
  - (266, 'Line exceeds 80 characters')
  - (274, 'Line exceeds 80 characters')
  - (278, 'Hardcoded string found')
  - (283, 'Hardcoded string found')
  - (289, 'Line exceeds 80 characters')
  - (312, 'Line exceeds 80 characters')
  - (320, 'Hardcoded string found')
  - (329, 'Hardcoded string found')
  - (343, 'Hardcoded string found')
  - (345, 'Line exceeds 80 characters')
  - (347, 'Line exceeds 80 characters')
  - (348, 'Line exceeds 80 characters')
  - (362, 'Hardcoded string found')
  - (367, 'Hardcoded string found')
  - (381, 'Hardcoded string found')
  - (389, 'Hardcoded string found')
  - (397, 'Hardcoded string found')
  - (402, 'Line exceeds 80 characters')
  - (410, 'Line exceeds 80 characters')
  - (415, 'Hardcoded string found')
  - (420, 'Hardcoded string found')
  - (427, 'Line exceeds 80 characters')
  - (439, 'Hardcoded string found')
  - (443, 'Line exceeds 80 characters')
  - (444, 'Line exceeds 80 characters')
  - (478, 'Hardcoded string found')
  - (499, 'Hardcoded string found')
  - (530, 'Hardcoded string found')
  - (558, 'Line exceeds 80 characters')
  - (564, 'Line exceeds 80 characters')
  - (599, 'Line exceeds 80 characters')
  - (608, 'Line exceeds 80 characters')
  - (662, 'Line exceeds 80 characters')
  - (679, 'Hardcoded string found')
  - (687, 'Hardcoded string found')
  - (691, 'Line exceeds 80 characters')
  - (697, 'Hardcoded string found')
  - (702, 'Line exceeds 80 characters')
  - (709, 'Hardcoded string found')
  - (714, 'Line exceeds 80 characters')
  - (787, 'Hardcoded string found')
  - (816, 'Hardcoded string found')
  - (829, 'Hardcoded string found')
  - (834, 'Hardcoded string found')
  - (847, 'Hardcoded string found')
  - (877, 'Hardcoded string found')
  - (882, 'Hardcoded string found')
  - (918, 'Hardcoded string found')
  - (928, 'Line exceeds 80 characters')
  - (939, 'Line exceeds 80 characters')
  - (954, 'Line exceeds 80 characters')
  - (960, 'Line exceeds 80 characters')
  - (971, 'Line exceeds 80 characters')
  - (979, 'Line exceeds 80 characters')
  - (982, 'Line exceeds 80 characters')
  - (992, 'Line exceeds 80 characters')
  - (996, 'Line exceeds 80 characters')
  - (1012, 'Line exceeds 80 characters')
  - (1016, 'Line exceeds 80 characters')
  - (1031, 'Line exceeds 80 characters')
  - (1035, 'Line exceeds 80 characters')
  - (1048, 'Line exceeds 80 characters')
  - (1052, 'Line exceeds 80 characters')
  - (1064, 'Line exceeds 80 characters')
  - (1068, 'Line exceeds 80 characters')
  - (1083, 'Line exceeds 80 characters')
  - (1086, 'Line exceeds 80 characters')
  - (1096, 'Line exceeds 80 characters')
  - (1100, 'Line exceeds 80 characters')
  - (1116, 'Line exceeds 80 characters')
  - (1120, 'Line exceeds 80 characters')
  - (1139, 'Line exceeds 80 characters')
  - (1143, 'Line exceeds 80 characters')
  - (1158, 'Line exceeds 80 characters')
  - (1176, 'Line exceeds 80 characters')
  - (1181, 'Line exceeds 80 characters')
  - (1188, 'Line exceeds 80 characters')
  - (1192, 'Line exceeds 80 characters')
  - (1199, 'Line exceeds 80 characters')
  - (1209, 'Line exceeds 80 characters')
  - (1213, 'Line exceeds 80 characters')
  - (1226, 'Line exceeds 80 characters')
  - (1253, 'Line exceeds 80 characters')
  - (1261, 'Line exceeds 80 characters')
  - (1270, 'Line exceeds 80 characters')
  - (1282, 'Line exceeds 80 characters')
  - (1296, 'Line exceeds 80 characters')
  - (1302, 'Line exceeds 80 characters')
  - (1313, 'Line exceeds 80 characters')
  - (1335, 'Line exceeds 80 characters')
  - (1345, 'Line exceeds 80 characters')
  - (1355, 'Line exceeds 80 characters')
  - (1356, 'Line exceeds 80 characters')
  - (1370, 'Line exceeds 80 characters')
  - (1379, 'Line exceeds 80 characters')
  - (1396, 'Line exceeds 80 characters')
  - (1411, 'Line exceeds 80 characters')
  - (1421, 'Hardcoded string found')
  - (1431, 'Hardcoded string found')
  - (1454, 'Hardcoded string found')
  - (1459, 'Line exceeds 80 characters')
  - (1464, 'Hardcoded string found')
  - (1473, 'Line exceeds 80 characters')
  - (1474, 'Line exceeds 80 characters')
  - (1479, 'Line exceeds 80 characters')
  - (1501, 'Line exceeds 80 characters')
  - (1519, 'Line exceeds 80 characters')
  - (1537, 'Line exceeds 80 characters')
  - (1545, 'Line exceeds 80 characters')
  - (1567, 'Line exceeds 80 characters')
  - (1568, 'Line exceeds 80 characters')
  - (1573, 'Line exceeds 80 characters')
  - (1581, 'Line exceeds 80 characters')
  - (1584, 'Line exceeds 80 characters')
  - (1621, 'Line exceeds 80 characters')
  - (1623, 'Line exceeds 80 characters')
  - (1632, 'Line exceeds 80 characters')
  - (1646, 'Hardcoded string found')
  - (1675, 'Hardcoded string found')
  - (1683, 'Hardcoded string found')
  - (1688, 'Hardcoded string found')
  - (1694, 'Line exceeds 80 characters')
  - (1698, 'Hardcoded string found')
  - (1703, 'Hardcoded string found')
  - (1708, 'Hardcoded string found')
  - (1718, 'Hardcoded string found')
  - (1723, 'Hardcoded string found')
  - (1727, 'Line exceeds 80 characters')
  - (1728, 'Line exceeds 80 characters')
  - (1747, 'Hardcoded string found')
  - (1774, 'Line exceeds 80 characters')
  - (1775, 'Line exceeds 80 characters')
  - (1776, 'Line exceeds 80 characters')
  - (1777, 'Line exceeds 80 characters')
  - (1778, 'Line exceeds 80 characters')
  - (1779, 'Line exceeds 80 characters')
  - (1780, 'Line exceeds 80 characters')
  - (1781, 'Line exceeds 80 characters')
  - (1782, 'Line exceeds 80 characters')
  - (1783, 'Line exceeds 80 characters')
  - (1784, 'Line exceeds 80 characters')
  - (1785, 'Line exceeds 80 characters')
  - (1786, 'Line exceeds 80 characters')
  - (1787, 'Line exceeds 80 characters')
  - (1788, 'Line exceeds 80 characters')
  - (1789, 'Line exceeds 80 characters')
  - (1790, 'Line exceeds 80 characters')
  - (1791, 'Line exceeds 80 characters')
  - (1792, 'Line exceeds 80 characters')
  - (1793, 'Line exceeds 80 characters')
  - (1794, 'Line exceeds 80 characters')
  - (1795, 'Line exceeds 80 characters')
  - (1796, 'Line exceeds 80 characters')
  - (1797, 'Line exceeds 80 characters')
  - (1798, 'Line exceeds 80 characters')
  - (1799, 'Line exceeds 80 characters')
  - (1800, 'Line exceeds 80 characters')
  - (1801, 'Line exceeds 80 characters')
  - (1802, 'Line exceeds 80 characters')
  - (1804, 'Line exceeds 80 characters')
  - (1805, 'Line exceeds 80 characters')
  - (1806, 'Line exceeds 80 characters')
  - (1807, 'Line exceeds 80 characters')
  - (1808, 'Line exceeds 80 characters')
  - (1809, 'Line exceeds 80 characters')
  - (1810, 'Line exceeds 80 characters')
  - (1811, 'Line exceeds 80 characters')
  - (1812, 'Line exceeds 80 characters')
  - (1813, 'Line exceeds 80 characters')
  - (1814, 'Line exceeds 80 characters')
  - (1815, 'Line exceeds 80 characters')
  - (1816, 'Line exceeds 80 characters')
  - (1817, 'Line exceeds 80 characters')
  - (1818, 'Line exceeds 80 characters')
  - (1819, 'Line exceeds 80 characters')
  - (1820, 'Line exceeds 80 characters')
  - (1821, 'Line exceeds 80 characters')
  - (1822, 'Line exceeds 80 characters')
  - (1823, 'Line exceeds 80 characters')
  - (1824, 'Line exceeds 80 characters')
  - (1825, 'Line exceeds 80 characters')
  - (1826, 'Line exceeds 80 characters')
  - (1827, 'Line exceeds 80 characters')
  - (1828, 'Line exceeds 80 characters')
  - (1830, 'Line exceeds 80 characters')
  - (1831, 'Line exceeds 80 characters')
  - (1832, 'Line exceeds 80 characters')
  - (1833, 'Line exceeds 80 characters')
  - (1834, 'Line exceeds 80 characters')
  - (1835, 'Line exceeds 80 characters')
  - (1836, 'Line exceeds 80 characters')
  - (1837, 'Line exceeds 80 characters')
  - (1838, 'Line exceeds 80 characters')
  - (1839, 'Line exceeds 80 characters')
  - (1840, 'Line exceeds 80 characters')
  - (1841, 'Line exceeds 80 characters')
  - (1842, 'Line exceeds 80 characters')
  - (1843, 'Line exceeds 80 characters')
  - (1844, 'Line exceeds 80 characters')
  - (1845, 'Line exceeds 80 characters')
  - (1846, 'Line exceeds 80 characters')
  - (1847, 'Line exceeds 80 characters')
  - (1848, 'Line exceeds 80 characters')
  - (1849, 'Line exceeds 80 characters')
  - (1850, 'Line exceeds 80 characters')
  - (1851, 'Line exceeds 80 characters')
  - (1852, 'Line exceeds 80 characters')
  - (1853, 'Line exceeds 80 characters')
  - (1854, 'Line exceeds 80 characters')
  - (1855, 'Line exceeds 80 characters')
  - (1856, 'Line exceeds 80 characters')
  - (1857, 'Line exceeds 80 characters')
  - (1858, 'Line exceeds 80 characters')
  - (1859, 'Line exceeds 80 characters')
  - (1860, 'Line exceeds 80 characters')
  - (1861, 'Line exceeds 80 characters')
  - (1862, 'Line exceeds 80 characters')
  - (1863, 'Line exceeds 80 characters')
  - (1864, 'Line exceeds 80 characters')
  - (1865, 'Line exceeds 80 characters')
  - (1866, 'Line exceeds 80 characters')
  - (1867, 'Line exceeds 80 characters')
  - (1868, 'Line exceeds 80 characters')
  - (1869, 'Line exceeds 80 characters')
  - (1870, 'Line exceeds 80 characters')
  - (1871, 'Line exceeds 80 characters')
  - (1872, 'Line exceeds 80 characters')
  - (1873, 'Line exceeds 80 characters')
  - (1874, 'Line exceeds 80 characters')
  - (1875, 'Line exceeds 80 characters')
  - (1876, 'Line exceeds 80 characters')
  - (1877, 'Line exceeds 80 characters')
  - (1878, 'Line exceeds 80 characters')
  - (1879, 'Line exceeds 80 characters')
  - (1880, 'Line exceeds 80 characters')
  - (1881, 'Line exceeds 80 characters')
  - (1882, 'Line exceeds 80 characters')
  - (1883, 'Line exceeds 80 characters')
  - (1884, 'Line exceeds 80 characters')
  - (1885, 'Line exceeds 80 characters')
  - (1886, 'Line exceeds 80 characters')
  - (1887, 'Line exceeds 80 characters')
  - (1888, 'Line exceeds 80 characters')
  - (1889, 'Line exceeds 80 characters')
  - (1891, 'Line exceeds 80 characters')
  - (1892, 'Line exceeds 80 characters')
  - (1893, 'Line exceeds 80 characters')
  - (1894, 'Line exceeds 80 characters')
  - (1895, 'Line exceeds 80 characters')
  - (1896, 'Line exceeds 80 characters')
  - (1897, 'Line exceeds 80 characters')
  - (1898, 'Line exceeds 80 characters')
  - (1899, 'Line exceeds 80 characters')
  - (1900, 'Line exceeds 80 characters')
  - (1901, 'Line exceeds 80 characters')
  - (1902, 'Line exceeds 80 characters')
  - (1903, 'Line exceeds 80 characters')
  - (1904, 'Line exceeds 80 characters')
  - (1905, 'Line exceeds 80 characters')
  - (1906, 'Line exceeds 80 characters')
  - (1907, 'Line exceeds 80 characters')
  - (1908, 'Line exceeds 80 characters')
  - (1909, 'Line exceeds 80 characters')
  - (1910, 'Line exceeds 80 characters')
  - (1911, 'Line exceeds 80 characters')
  - (1912, 'Line exceeds 80 characters')
  - (1913, 'Line exceeds 80 characters')
  - (1914, 'Line exceeds 80 characters')
  - (1915, 'Line exceeds 80 characters')
  - (1916, 'Line exceeds 80 characters')
  - (1917, 'Line exceeds 80 characters')
  - (1918, 'Line exceeds 80 characters')
  - (1919, 'Line exceeds 80 characters')
  - (1920, 'Line exceeds 80 characters')
  - (1921, 'Line exceeds 80 characters')
  - (1922, 'Line exceeds 80 characters')
  - (1923, 'Line exceeds 80 characters')
  - (1924, 'Line exceeds 80 characters')
  - (1925, 'Line exceeds 80 characters')
  - (1926, 'Line exceeds 80 characters')
  - (1927, 'Line exceeds 80 characters')
  - (1928, 'Line exceeds 80 characters')
  - (1929, 'Line exceeds 80 characters')
  - (1930, 'Line exceeds 80 characters')
  - (1931, 'Line exceeds 80 characters')
  - (1932, 'Line exceeds 80 characters')
  - (1933, 'Line exceeds 80 characters')
  - (1934, 'Line exceeds 80 characters')
  - (1935, 'Line exceeds 80 characters')
  - (1936, 'Line exceeds 80 characters')
  - (1937, 'Line exceeds 80 characters')
  - (1940, 'Line exceeds 80 characters')
  - (1941, 'Line exceeds 80 characters')
  - (1942, 'Line exceeds 80 characters')
  - (1943, 'Line exceeds 80 characters')
  - (1944, 'Line exceeds 80 characters')
  - (1945, 'Line exceeds 80 characters')
  - (1946, 'Line exceeds 80 characters')
  - (1947, 'Line exceeds 80 characters')
  - (1948, 'Line exceeds 80 characters')
  - (1949, 'Line exceeds 80 characters')
  - (1950, 'Line exceeds 80 characters')
  - (1951, 'Line exceeds 80 characters')
  - (1952, 'Line exceeds 80 characters')
  - (1953, 'Line exceeds 80 characters')
  - (1954, 'Line exceeds 80 characters')
  - (1955, 'Line exceeds 80 characters')
  - (1956, 'Line exceeds 80 characters')
  - (1957, 'Line exceeds 80 characters')
Issues in runtime/wasm/Cargo.toml:
  - (8, 'Hardcoded string found')
  - (15, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
  - (19, 'Line exceeds 80 characters')
  - (20, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
  - (23, 'Line exceeds 80 characters')
  - (24, 'Line exceeds 80 characters')
  - (25, 'Line exceeds 80 characters')
  - (26, 'Line exceeds 80 characters')
  - (27, 'Line exceeds 80 characters')
  - (28, 'Line exceeds 80 characters')
  - (29, 'Line exceeds 80 characters')
  - (30, 'Line exceeds 80 characters')
  - (55, 'Hardcoded string found')
Issues in runtime/wasm/build.sh:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (13, 'Line exceeds 80 characters')
Issues in src/chain_spec.rs:
  - (12, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (31, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (34, 'Line exceeds 80 characters')
  - (34, 'Hardcoded string found')
  - (36, 'Line exceeds 80 characters')
  - (36, 'Hardcoded string found')
  - (38, 'Line exceeds 80 characters')
  - (38, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (50, 'Line exceeds 80 characters')
  - (50, 'Hardcoded string found')
  - (51, 'Line exceeds 80 characters')
  - (51, 'Hardcoded string found')
  - (53, 'Line exceeds 80 characters')
  - (53, 'Hardcoded string found')
  - (54, 'Line exceeds 80 characters')
  - (54, 'Hardcoded string found')
  - (55, 'Line exceeds 80 characters')
  - (55, 'Hardcoded string found')
  - (56, 'Line exceeds 80 characters')
  - (56, 'Hardcoded string found')
  - (57, 'Line exceeds 80 characters')
  - (57, 'Hardcoded string found')
  - (58, 'Line exceeds 80 characters')
  - (58, 'Hardcoded string found')
  - (60, 'Line exceeds 80 characters')
  - (60, 'Hardcoded string found')
  - (73, 'Hardcoded string found')
  - (74, 'Hardcoded string found')
  - (80, 'Line exceeds 80 characters')
  - (83, 'Line exceeds 80 characters')
Issues in src/cli.rs:
  - (7, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
  - (29, 'Line exceeds 80 characters')
  - (53, 'Line exceeds 80 characters')
  - (65, 'Line exceeds 80 characters')
  - (66, 'Line exceeds 80 characters')
  - (104, 'Line exceeds 80 characters')
  - (111, 'Line exceeds 80 characters')
  - (112, 'Hardcoded string found')
Issues in src/error.rs:
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
Issues in src/main.rs:
  - (38, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
Issues in src/service.rs:
  - (2, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (27, 'Line exceeds 80 characters')
  - (41, 'Line exceeds 80 characters')
  - (42, 'Line exceeds 80 characters')
  - (43, 'Line exceeds 80 characters')
  - (44, 'Line exceeds 80 characters')
  - (52, 'Line exceeds 80 characters')
  - (82, 'Line exceeds 80 characters')

**Comment by satomichru** [comment]
I got it.
